### PR TITLE
Implementing new logic requirements for scenes handling

### PR DESCRIPTION
**Pull request by JeanPeare**
Implementation for new requirements about the scenes handling.

### CODE REVIEW

**Review by rubiperucci — APPROVED** [review]
Very nice and simple implementation!

**Review by itcr00w — APPROVED** [review]

**Review by Sam-sta — APPROVED** [review]

**Review by zkpain — APPROVED** [review]
This is awesome @JeanPeare :)

**Review by ap102 — APPROVED** [review]

**Review by Motopshyco — APPROVED** [review]

**Review by daniel33gomez — APPROVED** [review]
The only consideretion I have is this one:

I'd like to manage the type of actions as classes, so you'd be able to receive an abstracction that in this case is 'Shoot Weapon' or maybe other if the system would need it. In this way the OC principle would be improved in this code.

**Comment by JeanPeare** [comment]
> The only consideretion I have is this one:
> 
> I'd like to manage the type of actions as classes, so you'd be able to receive an abstracction that in this case is 'Shoot Weapon' or maybe other if the system would need it. In this way the OC principle would be improved in this code.

We are going to have in mind when start the best refactor possible, and we will see if it is possible implement that idea, thank you for the suggestion Daniel.

**Pull request merged**
